name: Notificar Release no Discord

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*' # Gatilho infalível para automações futuras
  workflow_dispatch:
    inputs:
      manual_version:
        description: 'Nome da Versão'
        required: true
        default: 'Hunter Launcher v1.2.0'
      manual_tag:
        description: 'Nome da Tag'
        required: true
        default: 'v1.2.0'

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem personalizada
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "📢 **Nova Release do Hunter Launcher Disponível!** @everyone \nConfiram as novidades que acabaram de sair direto do forno!"
          embed-title: "🚀 ${{ github.event.release.name || inputs.manual_version }} (${{ github.event.release.tag_name || inputs.manual_tag }})"
          embed-description: ${{ github.event.release.body || 'As notas de atualização completas já estão disponíveis no repositório!' }}
          embed-url: ${{ github.event.release.html_url || format('https://github.com/CaioMonteir0/Hunter-Launcher/releases/tag/{0}', inputs.manual_tag) }}
          embed-color: "3447003" 
          embed-author-name: "Hunter Launcher Updates"